version: "3.9"

services:
  master:
    image: ubuntu:22.04
    container_name: master-node
    hostname: master
    stdin_open: true
    tty: true
    networks:
      - hpcnet
    command: sleep infinity

  worker1:
    image: ubuntu:22.04
    container_name: worker-node-1
    hostname: worker1
    stdin_open: true
    tty: true
    networks:
      - hpcnet
    command: sleep infinity

  worker2:
    image: ubuntu:22.04
    container_name: worker-node-2
    hostname: worker2
    stdin_open: true
    tty: true
    networks:
      - hpcnet
    command: sleep infinity

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - hpcnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - hpcnet


networks:
  hpcnet:
    driver: bridge

