

services:
  master:
    build: .
    container_name: master-node
    hostname: master
    stdin_open: true
    tty: true
    networks:
      - hpcnet
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker1:
    build: .
    container_name: worker-node-1
    hostname: worker1
    stdin_open: true
    tty: true
    networks:
      - hpcnet
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker2:
    build: .
    container_name: worker-node-2
    hostname: worker2
    stdin_open: true
    tty: true
    networks:
      - hpcnet
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - hpcnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - hpcnet


networks:
  hpcnet:
    driver: bridge

